// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configuration} from '../models';

export function GetProjects():Promise<Array<configuration.ProjectRef>>;

export function ListLocalRepos(arg1:string):Promise<Array<string>>;

export function NewProject(arg1:string):Promise<configuration.ProjectRef>;
