// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function ListLocalRepos(arg1) {
  return window['go']['main']['App']['ListLocalRepos'](arg1);
}

export function NewProject(arg1) {
  return window['go']['main']['App']['NewProject'](arg1);
}
